## Preprocessing

In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

In [20]:
#  Import and read the charity_data.csv.
path = 'charity_data.csv'
application_df = pd.read_csv(path)
application_df.head()

EIN                                      NAME  ... ASK_AMT IS_SUCCESSFUL
0  10520599              BLUE KNIGHTS MOTORCYCLE CLUB  ...    5000             1
1  10531628    AMERICAN CHESAPEAKE CLUB CHARITABLE TR  ...  108590             1
2  10547893        ST CLOUD PROFESSIONAL FIREFIGHTERS  ...    5000             0
3  10553066            SOUTHSIDE ATHLETIC ASSOCIATION  ...    6692             1
4  10556103  GENETIC RESEARCH INSTITUTE OF THE DESERT  ...  142590             1

[5 rows x 12 columns]

In [21]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
app_df_clean = application_df.drop(columns=['EIN', 'NAME'])
app_df_clean.head(2)

APPLICATION_TYPE  AFFILIATION  ... ASK_AMT IS_SUCCESSFUL
0              T10  Independent  ...    5000             1
1               T3  Independent  ...  108590             1

[2 rows x 10 columns]

In [22]:
# Determine the number of unique values in each column.
app_df_clean.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [23]:
# Look at APPLICATION_TYPE value counts for binning
app_counts = app_df_clean['APPLICATION_TYPE'].value_counts()
app_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

cutoff is 500

In [24]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(app_counts[app_counts < 500].index)

# Replace in dataframe
for app in application_types_to_replace:
    app_df_clean['APPLICATION_TYPE'] = app_df_clean['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
app_df_clean['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [25]:
# Look at CLASSIFICATION value counts for binning
class_counts = app_df_clean['CLASSIFICATION'].value_counts()
class_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...  
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [26]:
# You may find it helpful to look at CLASSIFICATION value counts >1
class_counts[class_counts > 1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

cutoff will be 1000

In [27]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(class_counts[class_counts < 1000].index)

# Replace in dataframe
for cls in classifications_to_replace:
    app_df_clean['CLASSIFICATION'] = app_df_clean['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
app_df_clean['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [31]:
# Convert categorical data to numeric with `pd.get_dummies`
app_df_clean = pd.get_dummies(app_df_clean)
app_df_clean.head()

STATUS  ASK_AMT  ...  SPECIAL_CONSIDERATIONS_N  SPECIAL_CONSIDERATIONS_Y
0       1     5000  ...                         1                         0
1       1   108590  ...                         1                         0
2       1     5000  ...                         1                         0
3       1     6692  ...                         1                         0
4       1   142590  ...                         1                         0

[5 rows x 44 columns]

In [32]:
app_df_clean.head(1)

STATUS  ASK_AMT  ...  SPECIAL_CONSIDERATIONS_N  SPECIAL_CONSIDERATIONS_Y
0       1     5000  ...                         1                         0

[1 rows x 44 columns]

In [49]:
# Split our preprocessed data into our features and target arrays
x = app_df_clean.drop(columns=['IS_SUCCESSFUL']).values
y = app_df_clean['IS_SUCCESSFUL'].values

In [52]:
x[0]

array([   1, 5000,    0,    1,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    1,    0,    0,    0,    1,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    1,    1,    0,    0,    0,    1,
          0,    0,    0,    0,    0,    0,    0,    0,    1,    0])

In [53]:
y

array([1, 1, 0, ..., 0, 1, 0])

In [60]:
# split into training and testing data
x_train, x_test, y_train, y_test = train_test_split(x, y)

In [61]:
x_train[0]

array([   1, 5000,    0,    0,    0,    0,    0,    1,    0,    0,    0,
          1,    0,    0,    0,    0,    0,    1,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    1,    0,    0,    0,    1,    1,
          0,    0,    0,    0,    0,    0,    0,    0,    1,    0])

In [62]:
x_test[0]

array([     1, 680122,      0,      0,      0,      1,      0,      0,
            0,      0,      0,      0,      0,      1,      0,      0,
            0,      1,      0,      0,      0,      0,      0,      0,
            0,      0,      1,      0,      0,      0,      0,      1,
            0,      0,      0,      1,      0,      0,      0,      0,
            0,      1,      0])

In [63]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
x_scaler = scaler.fit(x_train)

# Scale the data
x_train_scaled = x_scaler.transform(x_train)
x_test_scaled = x_scaler.transform(x_test)
print(x_train_scaled[0])

[ 0.00623504 -0.0316657  -0.08762331 -0.1240739  -0.18076958 -1.92090643
 -0.21691721  5.23682245 -0.19215508 -0.14849557 -0.14822188  1.08457888
 -0.04543772 -1.07680222 -0.03055899 -0.01079982 -0.02160343  0.9878671
 -0.40005637 -0.46349629 -0.24378102 -0.24663181 -0.26508964 -0.10862723
 -0.06612829 -0.01079982 -2.11471682  2.23648531 -0.65585364 -0.11846277
 -0.03743571  0.67971042  0.63681194 -0.14808487 -0.12583881 -0.33243995
 -0.08180448 -0.1692065  -0.34850802 -0.06523281 -0.07043805  0.02646178
 -0.02646178]


## Compile, Train and Evaluate the Model

In [68]:
# Define the model - deep neural net, i.e., the number of input features and 
# hidden nodes for each layer.
num_input_features = len(x_train[0])
layer_1_nodes = 80
layer_2_nodes = 30

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=layer_1_nodes, 
                          input_dim=num_input_features, 
                          activation='relu')
)

# Second hidden layer
nn.add(
    tf.keras.layers.Dense(units=layer_2_nodes, 
                          input_dim=layer_1_nodes, 
                          activation='relu')
)

# Output layer
nn.add(
    tf.keras.layers.Dense(units=1, 
                          input_dim=layer_2_nodes, 
                          activation='sigmoid')
)

# Check the structure of the model
nn.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (None, 80)                3520      
                                                                 
 dense_7 (Dense)             (None, 30)                2430      
                                                                 
 dense_8 (Dense)             (None, 1)                 31        
                                                                 
Total params: 5,981
Trainable params: 5,981
Non-trainable params: 0
_________________________________________________________________


In [69]:
# Compile the model
nn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [70]:
# Train the model
fit_model = nn.fit(x_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5705 - accuracy: 0.7185
Epoch 2/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5571 - accuracy: 0.7266
Epoch 3/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5549 - accuracy: 0.7292
Epoch 4/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5533 - accuracy: 0.7278
Epoch 5/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5519 - accuracy: 0.7298
Epoch 6/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5513 - accuracy: 0.7307
Epoch 7/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5501 - accuracy: 0.7314
Epoch 8/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5492 - accuracy: 0.7320
Epoch 9/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5489 - accuracy: 0.7317
Epoch 10/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5484 - accura

In [72]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(x_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5679 - accuracy: 0.7334 - 445ms/epoch - 2ms/step
Loss: 0.5678936243057251, Accuracy: 0.7334110736846924


In [73]:
# Export our model to HDF5 file
nn.save('alphabet_soup.h5')